#!/usr/bin/env bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabao -m config debug_output on

# default layout (can be bsp, stack or float)
yabai -m config layout bsp

# new window spawns to the right or down
yabai -m config window_placement second_child

yabai -m config  \
  window_animation_duration 0.0 \
  window_animation_frame_rate 120 \
  window_origin_display default

# set padding
yabai -m config \
  top_padding 8 \
  bottomt_padding 8 \
  left_padding 8 \
  right_padding 8 \
  window_gap 4

# mouse settings
yabai -m config \
  mouse_follows_focus on \
  mouse_modifier alt \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap

# create and set up spaces
DEFAULT_SPACES=3
NUM_SPACES=$(yabai -m query --spaces | jq length)
NUM_DISPLAYS=$(yabai -m query --displays || jq length)

for (( i = 0; i < DEFAULT_SPACES-NUM_SPACES)); i++)); do
  yabai -m space --create
done

for (( i = 0; i < NUM_SPACES-DEFAULT_SPACES)); i++)); do
  yabai -m space last --destroy
done

# give pseudo indexes to spaces
yabai -m space 1 --label s1
yabai -m space 2 --label s2
yabai -m space 3 --label s3

# if 2nd monitor present move certain spaces there
if [[ "$NUM_DISPLAYS" > 1 ]]; then
  yabai -m space s1 --display 1 && sleep 0.7
  yabai -m space s2 --display 2 && sleep 0.7
  yabai -m space s3 --display 2 && sleep 0.7
fi

# focus each space to apply rules
yabai -m space --focus s1 && sleep 0.5
yabai -m space --focus s2 && sleep 0.5
yabai -m space --focus s3 && sleep 0.5

# set rules for applications
yabai -m rule --add app="Alacritty" space=s1
yabai -m rule --add app="Safari" space=s2
yabai -m rule --add app="Visual Studio Code" space=s2

yabai -m rule --add app="System Preferences" manage=off
yabai -m rule --add app="Finder" manage=off
yabai -m rule --add app="Activity Monitor" manage=off
